# Manuscript section: Supplementary sensitivity analyses
# Analysis family: assembled medication/comorbidity sensitivity figure
# Primary input dataset(s): outputs generated by sensitivity plotting scripts
# Primary output(s): combined supplementary sensitivity figure

library(patchwork)
library(here)

source(here(
  "01_analysis", "04_figures", "supplementary",
  "22_plot_group_sex_adjusted_medication_disorder_sensitivity.R"
))
source(here(
  "01_analysis", "04_figures", "supplementary",
  "20_plot_medication_disorder_sensitivity_profiles.R"
))
gaze_medication_plot <- medication_plot +
  guides(color = guide_legend(ncol = 1)) +
  theme(legend.text = element_text(size = 7.2))
gaze_disorder_plot <- disorder_plot +
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
  theme(legend.text = element_text(size = 7.2))

source(here(
  "01_analysis", "04_figures", "supplementary",
  "21_plot_cortisol_medication_disorder_sensitivity.R"
))
cortisol_medication_plot <- medication_plot +
  guides(color = guide_legend(ncol = 1)) +
  theme(legend.text = element_text(size = 7.2))
cortisol_disorder_plot <- disorder_plot +
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
  theme(legend.text = element_text(size = 7.2))

combined_sensitivity_plot <- (
  (adjusted_plot + labs(tag = "A")) |
    (
      (gaze_medication_plot + labs(tag = "B")) /
        (gaze_disorder_plot + labs(tag = "C"))
    ) |
    (
      (cortisol_medication_plot + labs(tag = "D")) /
        (cortisol_disorder_plot + labs(tag = "E"))
    )
) +
  plot_layout(widths = c(1.08, 1, 1)) &
  theme(
    plot.tag = element_text(face = "bold", size = 14),
    plot.tag.position = c(0, 1)
  )

output_dir <- here("02_outputs", "figures", "supplementary", "medication_disorder_sensitivity")
dir.create(file.path(output_dir, "png"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(output_dir, "svg"), recursive = TRUE, showWarnings = FALSE)

ggsave(
  file.path(output_dir, "png", "medication_disorder_sensitivity_combined.png"),
  combined_sensitivity_plot,
  width = 11.69,
  height = 8.27,
  dpi = 600
)
ggsave(
  file.path(output_dir, "svg", "medication_disorder_sensitivity_combined.svg"),
  combined_sensitivity_plot,
  width = 11.69,
  height = 8.27
)

print(combined_sensitivity_plot)
